/** @type {import('tailwindcss').Config} */
module.exports = {
   darkMode: 'class',
   content: [
      './src/pages/**/*.{js,ts,jsx,tsx,mdx}',
      './src/components/**/*.{js,ts,jsx,tsx,mdx}',
      './src/**/*.{js,ts,jsx,tsx,mdx}',
   ],
   theme: {
      fontFamily: {
         arabic: '"arabic"',
         transliteration: '"transliteration"',
         translation: '"translation"',
         fontB: '"Quicksand", sans-serif',
      },
      screens: {
         lg: { min: '897px' },
         sm: { max: '896px' },
         xs: { max: '500px' },
      },

      extend: {
         colors: {
            // headC: '#08102b',
            bodyC: '#08102b',
            // bodyCa: '#989b9f',
            bodyB: '#fdfcff',
            linkC: '#482dff',
            // linkB: '#482dff',
            // waveB: '#c6dafc',
            iconC: '#48525c',
            // iconCa: '#08102b',
            // iconCs: '#767676',
            headerC: '#343435',
            headerB: '#fffdfc',
            // notifU: '#e8f0fe',
            // notifC: '#01579b',
            contentB: '#fffdfc',
            // contentL: '#e6e6e6',
            transB: 'rgba(0, 0, 0, 0.05)',
            // navT: '#08102b',
            // navI: '#08102b',
            // navB: '#fffdfc',
            srchI: '#48525c',
            srchB: '#fffdfc',
            mobT: '#08102b',
            // mobHv: '#f1f1f0',
            mobB: '#fffdfc',
            fotT: '#08102b',
            fotB: '#fffdfc',
            darkT: '#fffdfc',
            darkTa: '#989b9f',
            darkU: '#41b375',
            // darkW: '#343435',
            darkB: '#1e1e1e',
            darkBa: '#2d2d30',
            darkBs: '#252526',
         },
         width: { navW: '230px', contentW: '1280px' },
         height: {
            headerH: '60px',
         },
         fontSize: {
            headerT: '18px',
         },
         borderRadius: {
            iconHr: '10px',
            srchDr: '15px',
         },
         transitionTimingFunction: {
            ease: 'ease',
         },
      },
   },
   plugins: [require('tailwind-scrollbar')({ nocompatible: true })],
};
